version: '3.7'
services:
  # Database. Cannot access via 3306 but phpmyadmin can pass
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./app/db/db.env
    # If you wish to access through outside just uncomment the section below
    # ports:
    #   - 3306:3306

  php-fpm:
    build: ./app/php
    image: php-fpm:custom
    restart: unless-stopped
    # Same dir as nginx
    volumes:
      - ./src/:/var/www/html

  # PHPMyAdmin for manage database
  sqlAdmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    # localhost:81
    ports:
      - 81:80
    # same as mariadb environment for access
    env_file: 
      ./app/db/db.env
    # custom connection to db
    environment:
      PMA_HOST: db

  app:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./app/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443

volumes:
  db: